blank_issues_enabled: false
contact_links:
  - name: 功能建议
    url: https://github.com/PythonSmall-Q/ClassinMover/discussions/new?category=%E5%8A%9F%E8%83%BD%E5%BB%BA%E8%AE%AE
    about: 提交功能建议相关的反馈
  - name: 提问
    url: https://github.com/PythonSmall-Q/ClassinMover/discussions/new?category=%E6%8F%90%E9%97%AE
    about: 我不想提交反馈，只是想问一些问题
